export const coaches = [
  {
    id: 1,
    name: 'Sarah Johnson',
    avatar: "https://randomuser.me/api/portraits/women/52.jpg",
    banner: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?crop=entropy&cs=tinysrgb&fit=crop&h=200&w=800",
    featured: true,
    specialties: ['weightTraining', 'nutrition', 'crossFit'],
    rating: 5,
    reviewCount: 127,
    monthlyPrice: 49,
    planDescription: 'Personalized workouts, meal plans, and weekly check-ins',
    available: true
  },
  {
    id: 2,
    name: 'Mike Reynolds',
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    banner: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3Dfit=crop&h=200&w=800",
    featured: false,
    specialties: ['crossFit', 'calisthenics', 'nutrition'],
    rating: 4,
    reviewCount: 89,
    monthlyPrice: 39,
    planDescription: 'CrossFit programming and nutrition guidance',
    available: true
  },
  {
    id: 3,
    name: 'Emma Chen',
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    banner: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: false,
    specialties: ['yoga', 'weightTraining', 'crossFit'],
    rating: 5,
    reviewCount: 112,
    monthlyPrice: 35,
    planDescription: 'Yoga sequences and meditation practices',
    available: true
  },
  {
    id: 4,
    name: 'James Wilson',
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    banner: "https://images.unsplash.com/photo-1578762560042-46ad127c95ea?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: true,
    specialties: ['yoga', 'crossFit', 'cardio'],
    rating: 5,
    reviewCount: 156,
    monthlyPrice: 59,
    planDescription: 'Custom bodybuilding plans with video analysis',
    available: true
  },
  {
    id: 5,
    name: 'Aisha Patel',
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    banner: "https://images.unsplash.com/photo-1510894347713-fc3ed6fdf539?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: false,
    specialties: ['cardio', 'weightTraining', 'yoga'],
    rating: 4,
    reviewCount: 72,
    monthlyPrice: 45,
    planDescription: 'Weight loss focused training and nutrition',
    available: true
  },
  {
    id: 6,
    name: 'David Rodriguez',
    avatar: "https://randomuser.me/api/portraits/men/74.jpg",
    banner: "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    featured: false,
    specialties: ['calisthenics', 'nutrition', 'crossFit'],
    rating: 5,
    reviewCount: 94,
    monthlyPrice: 42,
    planDescription: 'Bodyweight mastery and movement coaching',
    available: true
  }
];
